set nocompatible
set number
set backspace=indent,eol,start
set autoindent
set cindent
set nobackup
set history=50
set ruler
set showcmd
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set bg=dark
set showmatch
set hlsearch
